# Generated by Django 4.2.5 on 2023-09-18 09:56

import ckeditor.fields
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspiration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspiration_title', models.CharField(max_length=255)),
                ('inspiration_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('inspiration_image', models.ImageField(blank=True, null=True, upload_to='inspirations-images')),
                ('inspiration_file', models.FileField(blank=True, null=True, upload_to='inspirations-files')),
                ('inspiration_video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('inspiration_link', models.URLField(blank=True, null=True)),
                ('inspiration_audio', models.TextField(blank=True, help_text='Copy and paste the embed code from a SoundCloud file. E.g. &lt;iframe ... For help with this please visit: <a href="https://help.soundcloud.com/hc/en-us/articles/115003568008-Embedding-a-track-or-playlist" target="_blank">SoundCloud Help</a>', null=True)),
                ('admin_published', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('meta_created_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('meta_lastupdated_datetime', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'ordering': ['inspiration_title', '-id'],
            },
        ),
    ]
